"""init

Revision ID: 885428e15343
Revises: 
Create Date: 2022-12-08 20:13:47.497175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885428e15343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(scale=2), nullable=True),
    sa.Column('cost_per_click', sa.Numeric(scale=2), nullable=True),
    sa.Column('cost_per_view', sa.Numeric(scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
